register:
  email: ''
  password: ''
  name: ''
  birthday: '2000-01-01'
  runs: 1
email:
  provider: manual
  use_email_service: false
  email_source: manual
  outlook:
    api_base: https://mail.chatai.codes
    accounts: []
  imap:
    login_email: ''
    login_password: ''
    host: imap.2925.com
    port: 993
    ssl: true
    mailbox: INBOX
    alias_enabled: true
    alias_mode: append_random
    alias_domain_mode: default
    alias_domain: ''
    alias_random_length: 6
    alias_separator: ''
  otp:
    poll_interval: 3
    max_wait: 90
    settle_seconds: 5
browser:
  user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/142.0.0.0 Safari/537.36
  sec_ch_ua: '"Chromium";v="142", "Google Chrome";v="142", "Not_A Brand";v="99"'
  sec_ch_ua_platform: '"Windows"'
  sec_ch_ua_mobile: ?0
  impersonate: chrome142
  request_timeout: 30
openai_protocol:
  client_id: app_X8zY6vW2pQ9tR3dE7nK1jL5gH
  scope: openid email profile offline_access model.request model.read organization.read
    organization.write
  audience: https://api.openai.com/v1
  redirect_uri: https://chatgpt.com/api/auth/callback/openai
  sentinel_sv: 20260219f9f6
proxy:
  pool:
  - http://qcfvn17921-region-US-sid-BtvQrhNf-t-5:ujgdlt5p@us.lajiaohttp.net:2000
  - http://qcfvn17921-region-US-sid-nwA5sPzj-t-5:ujgdlt5p@us.lajiaohttp.net:2000
  - http://qcfvn17921-region-US-sid-zRmcM5JD-t-5:ujgdlt5p@us.lajiaohttp.net:2000
  - http://qcfvn17921-region-US-sid-5nC7cSWw-t-5:ujgdlt5p@us.lajiaohttp.net:2000
  - http://qcfvn17921-region-US-sid-bZ9nCKj2-t-5:ujgdlt5p@us.lajiaohttp.net:2000
  - http://qcfvn17921-region-US-sid-3VbzuVJN-t-5:ujgdlt5p@us.lajiaohttp.net:2000
  - http://qcfvn17921-region-US-sid-UjhLMLsq-t-5:ujgdlt5p@us.lajiaohttp.net:2000
  - http://qcfvn17921-region-US-sid-ZxZVXkGB-t-5:ujgdlt5p@us.lajiaohttp.net:2000
  - http://qcfvn17921-region-US-sid-5q3mvEgz-t-5:ujgdlt5p@us.lajiaohttp.net:2000
  - http://qcfvn17921-region-US-sid-9vYYGjYX-t-5:ujgdlt5p@us.lajiaohttp.net:2000
  - http://qcfvn17921-region-US-sid-eBKapB5b-t-5:ujgdlt5p@us.lajiaohttp.net:2000
  - http://qcfvn17921-region-US-sid-2Fuxy7aN-t-5:ujgdlt5p@us.lajiaohttp.net:2000
  - http://qcfvn17921-region-US-sid-RBLvna5s-t-5:ujgdlt5p@us.lajiaohttp.net:2000
  - http://qcfvn17921-region-US-sid-8fRmMmw1-t-5:ujgdlt5p@us.lajiaohttp.net:2000
  - http://qcfvn17921-region-US-sid-3ww65Gfx-t-5:ujgdlt5p@us.lajiaohttp.net:2000
  - http://qcfvn17921-region-US-sid-xg12Vs8n-t-5:ujgdlt5p@us.lajiaohttp.net:2000
  - http://qcfvn17921-region-US-sid-Cq19XJPF-t-5:ujgdlt5p@us.lajiaohttp.net:2000
  - http://qcfvn17921-region-US-sid-1B2WLpvX-t-5:ujgdlt5p@us.lajiaohttp.net:2000
  - http://qcfvn17921-region-US-sid-iVbMtMFu-t-5:ujgdlt5p@us.lajiaohttp.net:2000
  - http://qcfvn17921-region-US-sid-NUi1t5X6-t-5:ujgdlt5p@us.lajiaohttp.net:2000
twofa:
  enabled: false
flow_trigger:
  enabled: true
  url: http://156.225.31.95:8000/api/trigger-flow
  bearer: ''
  cookie: ''
  payload:
    action: chat
  timeout: 30
